# Generated by Django 4.2.1 on 2023-09-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='menuitem',
        ),
    ]
